[package]
name = "rust_hypergraph"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.40"
criterion = "0.5.1"

[[bench]]
name = "dfs_bench"
harness = false

[[bench]]
name = "bfs_bench"
harness = false